# Generated by Django 4.2.23 on 2025-08-02 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_remove_bug_is_active_remove_bug_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('data', models.TextField(null=True)),
                ('ip_address', models.CharField(max_length=100, null=True)),
                ('project', models.ForeignKey(help_text='Activity under which project.', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='tracker.project')),
                ('user', models.ForeignKey(help_text='The user who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activity Logs',
                'ordering': ('-created_at',),
            },
        ),
    ]
