# Generated by Django 4.2.23 on 2025-08-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_deleted',
        ),
    ]
